# Generated by Django 2.2.3 on 2019-08-31 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='state',
            field=models.CharField(max_length=10),
        ),
    ]
